-- Add cif_section field to schools table
ALTER TABLE schools ADD COLUMN IF NOT EXISTS cif_section TEXT;
CREATE INDEX IF NOT EXISTS idx_schools_cif_section ON schools(cif_section);

-- Update BVAL schools with league
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Andrew Hill%' OR short_name ILIKE '%Andrew Hill%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Branham%' OR short_name ILIKE '%Branham%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Christopher%' OR short_name ILIKE '%Christopher%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Del Mar%' OR short_name ILIKE '%Del Mar%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Evergreen Valley%' OR short_name ILIKE '%Evergreen Valley%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Gilroy%' OR short_name ILIKE '%Gilroy%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Gunderson%' OR short_name ILIKE '%Gunderson%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Independence%' OR short_name ILIKE '%Independence%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%James Lick%' OR short_name ILIKE '%James Lick%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Leigh%' OR short_name ILIKE '%Leigh%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Leland%' OR short_name ILIKE '%Leland%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Lincoln%' OR short_name ILIKE '%Lincoln%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Live Oak%' OR short_name ILIKE '%Live Oak%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Mt. Pleasant%' OR short_name ILIKE '%Mt. Pleasant%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Oak Grove%' OR short_name ILIKE '%Oak Grove%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Overfelt%' OR short_name ILIKE '%Overfelt%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Piedmont Hills%' OR short_name ILIKE '%Piedmont Hills%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Pioneer%' OR short_name ILIKE '%Pioneer%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Prospect%' OR short_name ILIKE '%Prospect%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%San Jose High%' OR short_name ILIKE '%San Jose High%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Santa Teresa%' OR short_name ILIKE '%Santa Teresa%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Silver Creek%' OR short_name ILIKE '%Silver Creek%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Sobrato%' OR short_name ILIKE '%Sobrato%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Westmont%' OR short_name ILIKE '%Westmont%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Willow Glen%' OR short_name ILIKE '%Willow Glen%';
UPDATE schools SET league = 'BVAL' WHERE name ILIKE '%Yerba Buena%' OR short_name ILIKE '%Yerba Buena%';

-- Update CCS schools with division and section
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Ace Charter School%' OR short_name ILIKE '%Ace Charter School%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Alisal%' OR short_name ILIKE '%Alisal%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Andrew Hill%' OR short_name ILIKE '%Andrew Hill%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Anzar%' OR short_name ILIKE '%Anzar%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Aptos%' OR short_name ILIKE '%Aptos%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Aragon%' OR short_name ILIKE '%Aragon%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Archbishop Mitty%' OR short_name ILIKE '%Archbishop Mitty%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Archbishop Riordan%' OR short_name ILIKE '%Archbishop Riordan%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%BASIS Independent Silicon Valley%' OR short_name ILIKE '%BASIS Independent Silicon Valley%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Bellarmine College Prep%' OR short_name ILIKE '%Bellarmine College Prep%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Branham%' OR short_name ILIKE '%Branham%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Burlingame%' OR short_name ILIKE '%Burlingame%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%CEIBA Prep Academy%' OR short_name ILIKE '%CEIBA Prep Academy%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Capuchino%' OR short_name ILIKE '%Capuchino%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Carlmont%' OR short_name ILIKE '%Carlmont%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Carmel%' OR short_name ILIKE '%Carmel%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Castilleja%' OR short_name ILIKE '%Castilleja%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Christopher%' OR short_name ILIKE '%Christopher%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Cindy Avitia%' OR short_name ILIKE '%Cindy Avitia%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Cristo Rey San Jose%' OR short_name ILIKE '%Cristo Rey San Jose%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Crystal Springs Uplands%' OR short_name ILIKE '%Crystal Springs Uplands%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Cupertino%' OR short_name ILIKE '%Cupertino%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Del Mar%' OR short_name ILIKE '%Del Mar%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Design Tech%' OR short_name ILIKE '%Design Tech%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%East Palo Alto Academy%' OR short_name ILIKE '%East Palo Alto Academy%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Eastside College Prep%' OR short_name ILIKE '%Eastside College Prep%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%El Camino%' OR short_name ILIKE '%El Camino%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Everett Alvarez%' OR short_name ILIKE '%Everett Alvarez%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Evergreen Valley%' OR short_name ILIKE '%Evergreen Valley%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Fremont%' OR short_name ILIKE '%Fremont%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Gilroy%' OR short_name ILIKE '%Gilroy%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Gonzales%' OR short_name ILIKE '%Gonzales%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Greenfield%' OR short_name ILIKE '%Greenfield%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Gunderson%' OR short_name ILIKE '%Gunderson%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Gunn%' OR short_name ILIKE '%Gunn%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Half Moon Bay%' OR short_name ILIKE '%Half Moon Bay%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Harbor%' OR short_name ILIKE '%Harbor%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Harker%' OR short_name ILIKE '%Harker%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Hillsdale%' OR short_name ILIKE '%Hillsdale%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Hollister%' OR short_name ILIKE '%Hollister%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Homestead%' OR short_name ILIKE '%Homestead%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Independence%' OR short_name ILIKE '%Independence%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%James Lick%' OR short_name ILIKE '%James Lick%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Jefferson%' OR short_name ILIKE '%Jefferson%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Junipero Serra%' OR short_name ILIKE '%Junipero Serra%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%KIPP Esperanza%' OR short_name ILIKE '%KIPP Esperanza%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%KIPP Navigate College Prep%' OR short_name ILIKE '%KIPP Navigate College Prep%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%KIPP San Jose Collegiate%' OR short_name ILIKE '%KIPP San Jose Collegiate%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Kehillah Jewish%' OR short_name ILIKE '%Kehillah Jewish%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%King City%' OR short_name ILIKE '%King City%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Kirby%' OR short_name ILIKE '%Kirby%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Latino College Prep%' OR short_name ILIKE '%Latino College Prep%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Leigh%' OR short_name ILIKE '%Leigh%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Leland%' OR short_name ILIKE '%Leland%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Lincoln%' OR short_name ILIKE '%Lincoln%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Live Oak%' OR short_name ILIKE '%Live Oak%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Los Altos%' OR short_name ILIKE '%Los Altos%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Los Gatos%' OR short_name ILIKE '%Los Gatos%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Luis Valdez Leadership Academy%' OR short_name ILIKE '%Luis Valdez Leadership Academy%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Lynbrook%' OR short_name ILIKE '%Lynbrook%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%MacDonald%' OR short_name ILIKE '%MacDonald%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Marina%' OR short_name ILIKE '%Marina%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Menlo School%' OR short_name ILIKE '%Menlo School%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Menlo-Atherton%' OR short_name ILIKE '%Menlo-Atherton%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Mercy%' OR short_name ILIKE '%Mercy%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Mid Peninsula%' OR short_name ILIKE '%Mid Peninsula%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Mills%' OR short_name ILIKE '%Mills%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Milpitas%' OR short_name ILIKE '%Milpitas%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Monta Vista%' OR short_name ILIKE '%Monta Vista%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Monte Vista Christian%' OR short_name ILIKE '%Monte Vista Christian%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Monterey%' OR short_name ILIKE '%Monterey%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Monterey Bay Academy%' OR short_name ILIKE '%Monterey Bay Academy%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Mountain View%' OR short_name ILIKE '%Mountain View%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Mountain View Academy%' OR short_name ILIKE '%Mountain View Academy%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Mt. Madonna%' OR short_name ILIKE '%Mt. Madonna%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Mt. Pleasant%' OR short_name ILIKE '%Mt. Pleasant%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%North Monterey County%' OR short_name ILIKE '%North Monterey County%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%North Salinas%' OR short_name ILIKE '%North Salinas%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Notre Dame Belmont%' OR short_name ILIKE '%Notre Dame Belmont%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Notre Dame Salinas%' OR short_name ILIKE '%Notre Dame Salinas%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Notre Dame San Jose%' OR short_name ILIKE '%Notre Dame San Jose%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Nueva%' OR short_name ILIKE '%Nueva%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Oak Grove%' OR short_name ILIKE '%Oak Grove%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Oakwood%' OR short_name ILIKE '%Oakwood%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Oceana%' OR short_name ILIKE '%Oceana%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Overfelt%' OR short_name ILIKE '%Overfelt%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Pacific Bay Christian%' OR short_name ILIKE '%Pacific Bay Christian%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Pacific Collegiate%' OR short_name ILIKE '%Pacific Collegiate%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Pacific Grove%' OR short_name ILIKE '%Pacific Grove%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Pajaro Valley%' OR short_name ILIKE '%Pajaro Valley%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Palma%' OR short_name ILIKE '%Palma%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Palo Alto%' OR short_name ILIKE '%Palo Alto%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Pescadero%' OR short_name ILIKE '%Pescadero%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Piedmont Hills%' OR short_name ILIKE '%Piedmont Hills%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Pinewood%' OR short_name ILIKE '%Pinewood%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Pioneer%' OR short_name ILIKE '%Pioneer%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Presentation%' OR short_name ILIKE '%Presentation%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Priory%' OR short_name ILIKE '%Priory%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Prospect%' OR short_name ILIKE '%Prospect%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Rancho San Juan%' OR short_name ILIKE '%Rancho San Juan%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Sacred Heart Cathedral%' OR short_name ILIKE '%Sacred Heart Cathedral%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Sacred Heart Prep%' OR short_name ILIKE '%Sacred Heart Prep%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Saint Francis%' OR short_name ILIKE '%Saint Francis%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Salinas%' OR short_name ILIKE '%Salinas%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%San Francisco Christian%' OR short_name ILIKE '%San Francisco Christian%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%San Jose High%' OR short_name ILIKE '%San Jose High%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%San Lorenzo Valley%' OR short_name ILIKE '%San Lorenzo Valley%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%San Mateo%' OR short_name ILIKE '%San Mateo%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Santa Catalina%' OR short_name ILIKE '%Santa Catalina%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Santa Clara%' OR short_name ILIKE '%Santa Clara%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Santa Cruz%' OR short_name ILIKE '%Santa Cruz%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Santa Teresa%' OR short_name ILIKE '%Santa Teresa%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Saratoga%' OR short_name ILIKE '%Saratoga%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Scotts Valley%' OR short_name ILIKE '%Scotts Valley%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Seaside%' OR short_name ILIKE '%Seaside%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Sequoia%' OR short_name ILIKE '%Sequoia%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Silver Creek%' OR short_name ILIKE '%Silver Creek%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Sobrato%' OR short_name ILIKE '%Sobrato%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Soledad%' OR short_name ILIKE '%Soledad%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Soquel%' OR short_name ILIKE '%Soquel%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%South San Francisco%' OR short_name ILIKE '%South San Francisco%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%St. Francis SCP%' OR short_name ILIKE '%St. Francis SCP%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%St. Ignatius%' OR short_name ILIKE '%St. Ignatius%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Stevenson%' OR short_name ILIKE '%Stevenson%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Stratford%' OR short_name ILIKE '%Stratford%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Summit Prep%' OR short_name ILIKE '%Summit Prep%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Summit Shasta%' OR short_name ILIKE '%Summit Shasta%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Summit Tahoma%' OR short_name ILIKE '%Summit Tahoma%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Terra Nova%' OR short_name ILIKE '%Terra Nova%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%The Kings Academy%' OR short_name ILIKE '%The Kings Academy%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%The York School%' OR short_name ILIKE '%The York School%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Thomas More%' OR short_name ILIKE '%Thomas More%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%Trinity Christian%' OR short_name ILIKE '%Trinity Christian%';
UPDATE schools SET cif_division = 'D5', cif_section = 'CCS' WHERE name ILIKE '%University Prep Academy%' OR short_name ILIKE '%University Prep Academy%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Valley Christian%' OR short_name ILIKE '%Valley Christian%';
UPDATE schools SET cif_division = 'D1', cif_section = 'CCS' WHERE name ILIKE '%Watsonville%' OR short_name ILIKE '%Watsonville%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Westmont%' OR short_name ILIKE '%Westmont%';
UPDATE schools SET cif_division = 'D4', cif_section = 'CCS' WHERE name ILIKE '%Westmoor%' OR short_name ILIKE '%Westmoor%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Wilcox%' OR short_name ILIKE '%Wilcox%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Willow Glen%' OR short_name ILIKE '%Willow Glen%';
UPDATE schools SET cif_division = 'D2', cif_section = 'CCS' WHERE name ILIKE '%Woodside%' OR short_name ILIKE '%Woodside%';
UPDATE schools SET cif_division = 'D3', cif_section = 'CCS' WHERE name ILIKE '%Yerba Buena%' OR short_name ILIKE '%Yerba Buena%';